#!/usr/bin/env bash

kube_vault=/home/tenmoomnet/.kube_vault

rm -rf $kube_vault/system-snap/
mkdir -p $kube_vault/system-snap/etc/kubernetes/manifests/
mkdir -p $kube_vault/system-snap/etc/systemd/system/

if [ -f /etc/kubernetes/manifests/etcd.yaml ]; then 
  sudo cp /etc/kubernetes/manifests/etcd.yaml $kube_vault/system-snap/etc/kubernetes/manifests/
fi

if [ -f /etc/kubernetes/manifests/kube-apiserver.yaml ]; then
  sudo cp /etc/kubernetes/manifests/kube-apiserver.yaml $kube_vault/system-snap/etc/kubernetes/manifests/
fi

if [ -f /etc/systemd/system/etcd.service ]; then
  sudo cp /etc/systemd/system/etcd.service $kube_vault/system-snap/etc/systemd/system/
fi  

sudo chown -R $(whoami) $kube_vault/system-snap/
cd $kube_vault/system-snap/ &>/dev/null

tar cfz system-snap.tar.gz etc 

cd - &>/dev/null
