#Whiltespace separated list of servers hosting the etcd cluster. Each entry consists of server and IP delimited by colon(sever:IP)
etcd_servers=vm:10.160.0.7
sleep_time=3
etcd_ca=/etc/kubernetes/pki/etcd/ca.crt
etcd_key=/etc/kubernetes/pki/etcd/ca.key
default_backup_loc=/etc/backup
default_restore_path=/var/lib/etcd-restore
masters=vm:10.160.0.7
etcd_version=3.6.13
kube_install_git_repo=https://github.com/ratulb/k8s-easy-install.git
